# Generated by Django 6.0.6 on 2026-06-28 19:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_kind', models.CharField(choices=[('activation', 'Activation'), ('deposit', 'Deposit')], max_length=20)),
                ('payment_method', models.CharField(choices=[('stk_push', 'STK Push'), ('c2b', 'C2B PayBill')], max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('unmatched', 'Unmatched')], default='initiated', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('phone_number', models.CharField(max_length=20)),
                ('account_reference', models.CharField(db_index=True, max_length=40)),
                ('merchant_request_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('result_code', models.CharField(blank=True, max_length=20)),
                ('result_description', models.CharField(blank=True, max_length=255)),
                ('raw_request', models.JSONField(blank=True, default=dict)),
                ('raw_callback', models.JSONField(blank=True, default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='payments_mp_user_id_c2427b_idx'), models.Index(fields=['transaction_kind', 'status'], name='payments_mp_transac_c552d8_idx'), models.Index(fields=['account_reference', 'status'], name='payments_mp_account_5b79c1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 1)), name='mpesa_transaction_amount_minimum')],
            },
        ),
    ]
