# Generated by Django 6.0.6 on 2026-06-28 19:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0002_withdrawalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=60)),
                ('color', models.CharField(default='#0b5fff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'job categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('job_type', models.CharField(choices=[('survey', 'Survey'), ('watch_ad', 'Watch and earn'), ('trivia', 'Trivia'), ('blogging', 'Blogging/social proof'), ('app_testing', 'App/game testing'), ('website_feedback', 'Website feedback'), ('data_entry', 'Data entry/tagging'), ('transcription', 'Transcription'), ('translation', 'Translation'), ('product_review', 'Product review'), ('chat_session', 'Paid chat session'), ('product_affiliate', 'Product affiliate'), ('other', 'Other')], default='other', max_length=40)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('worker_limit', models.PositiveIntegerField(default=1)),
                ('claims_count', models.PositiveIntegerField(default=0)),
                ('approved_count', models.PositiveIntegerField(default=0)),
                ('pending_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('full', 'Full'), ('paused', 'Paused'), ('expired', 'Expired'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('review_mode', models.CharField(choices=[('manual', 'Manual review'), ('auto', 'Auto approve')], default='manual', max_length=20)),
                ('proof_type', models.CharField(choices=[('none', 'No proof'), ('text', 'Text answer'), ('url', 'URL'), ('file', 'File upload'), ('text_url', 'Text and URL')], default='text', max_length=20)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('claim_expires_after_minutes', models.PositiveIntegerField(default=1440)),
                ('max_claims_per_user', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='jobs.job')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.jobcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('claimed', 'Claimed'), ('expired', 'Expired'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='claimed', max_length=20)),
                ('claimed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('expires_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('proof_url', models.URLField(blank=True)),
                ('proof_file', models.FileField(blank=True, upload_to='job-proof/%Y/%m/')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('claimed', 'Claimed'), ('expired', 'Expired'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='submitted', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='submission', to='jobs.jobclaim')),
                ('ledger_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_submission', to='wallets.ledgertransaction')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_job_submissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'job_type'], name='jobs_job_status_c00be6_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['category', 'status'], name='jobs_job_categor_2e2729_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['starts_at', 'ends_at'], name='jobs_job_starts__5ddd52_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('worker_limit__gte', 1)), name='job_worker_limit_positive'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('reward_amount__gt', 0)), name='job_reward_positive'),
        ),
        migrations.AddIndex(
            model_name='jobclaim',
            index=models.Index(fields=['user', 'status'], name='jobs_jobcla_user_id_3e3cef_idx'),
        ),
        migrations.AddIndex(
            model_name='jobclaim',
            index=models.Index(fields=['job', 'status'], name='jobs_jobcla_job_id_9ba6f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobclaim',
            constraint=models.UniqueConstraint(fields=('job', 'user'), name='one_claim_per_user_per_job'),
        ),
        migrations.AddIndex(
            model_name='jobsubmission',
            index=models.Index(fields=['status', '-created_at'], name='jobs_jobsub_status_62b831_idx'),
        ),
        migrations.AddIndex(
            model_name='jobsubmission',
            index=models.Index(fields=['user', 'status'], name='jobs_jobsub_user_id_398aed_idx'),
        ),
    ]
