# Generated by Django 6.0.6 on 2026-06-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='banner_image',
            field=models.FileField(blank=True, upload_to='jobs/banners/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='job',
            name='content_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='content_file',
            field=models.FileField(blank=True, upload_to='jobs/content/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='job',
            name='content_format',
            field=models.CharField(choices=[('task', 'Task instructions'), ('survey', 'Survey'), ('article', 'Article/story'), ('video', 'Video'), ('file', 'File/resource'), ('external', 'External link')], default='task', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='content_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
