# Generated by Django 6.0.6 on 2026-06-30 16:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_banner_image_job_content_body_job_content_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('survey', 'Survey'), ('watch_ad', 'Watch and earn'), ('trivia', 'Trivia'), ('blogging', 'Blogging/social proof'), ('app_testing', 'App/game testing'), ('website_feedback', 'Website feedback'), ('data_entry', 'Data entry/tagging'), ('transcription', 'Transcription'), ('translation', 'Translation'), ('product_review', 'Product review'), ('chat_session', 'Paid chat session'), ('swahili_teaching', 'Teach Swahili'), ('ai_training', 'AI training'), ('product_affiliate', 'Product affiliate'), ('other', 'Other')], default='other', max_length=40),
        ),
        migrations.CreateModel(
            name='ChatProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=80)),
                ('headline', models.CharField(max_length=160)),
                ('bio', models.TextField()),
                ('topic_prompt', models.CharField(max_length=220)),
                ('avatar_initials', models.CharField(max_length=4)),
                ('rate_per_message', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'display_name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='jobs_chatpr_is_acti_cedf10_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('offline', 'Partner offline'), ('closed', 'Closed')], default='open', max_length=20)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threads', to='jobs.chatprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('partner', 'Partner')], max_length=20)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='jobs.chatthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['user', '-last_message_at'], name='jobs_chatth_user_id_929065_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['profile', 'status'], name='jobs_chatth_profile_eadcf0_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread', 'created_at'], name='jobs_chatme_thread__9023d6_idx'),
        ),
    ]
