# Generated by Django 6.0.6 on 2026-06-28 19:01

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('activation_fee', models.DecimalField(decimal_places=2, default=Decimal('185.00'), max_digits=12)),
                ('activation_credit_mode', models.CharField(choices=[('platform_credit', 'Platform credit'), ('withdrawable_balance', 'Withdrawable balance'), ('mixed', 'Mixed')], default='mixed', max_length=30)),
                ('activation_withdrawable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('referral_bonus_type', models.CharField(choices=[('fixed', 'Fixed amount'), ('percent', 'Percentage')], default='fixed', max_length=20)),
                ('referral_bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('75.00'), max_digits=12)),
                ('referral_bonus_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('referral_bonus_release_delay_hours', models.PositiveIntegerField(default=24)),
                ('minimum_withdrawal_amount', models.DecimalField(decimal_places=2, default=Decimal('300.00'), max_digits=12)),
                ('maximum_daily_withdrawal_per_user', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=12)),
                ('withdrawal_fee_fixed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('withdrawal_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('reserve_ratio_target', models.DecimalField(decimal_places=2, default=Decimal('1.10'), max_digits=5)),
                ('minimum_platform_cash_buffer', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deposit_enabled', models.BooleanField(default=True)),
                ('payout_enabled', models.BooleanField(default=False)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_finance_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'finance settings',
                'verbose_name_plural': 'finance settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('finance_setting_changed', 'Finance setting changed'), ('wallet_adjusted', 'Wallet adjusted'), ('system', 'System')], max_length=40)),
                ('model_label', models.CharField(blank=True, max_length=120)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('object_repr', models.CharField(blank=True, max_length=240)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='core_auditl_action_d80c2d_idx'), models.Index(fields=['model_label', 'object_id'], name='core_auditl_model_l_bd2fc4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('group', models.CharField(default='general', max_length=80)),
                ('value_type', models.CharField(choices=[('string', 'String'), ('decimal', 'Decimal'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('value', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_site_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['group', 'key'],
                'indexes': [models.Index(fields=['group', 'key'], name='core_sitese_group_bd2db5_idx')],
            },
        ),
    ]
