# Generated by Django 6.0.6 on 2026-06-28 19:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='auto_approve_job_reward_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='auto_approve_small_jobs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='job_reward_release_delay_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='max_ad_watch_rewards_per_day',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='max_claims_per_user_per_day',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('finance_setting_changed', 'Finance setting changed'), ('wallet_adjusted', 'Wallet adjusted'), ('withdrawal_reviewed', 'Withdrawal reviewed'), ('system', 'System')], max_length=40),
        ),
    ]
