# Generated by Django 6.0.6 on 2026-06-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_financesettings_auto_approve_job_reward_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='job_claims_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
