# Generated by Django 6.0.6 on 2026-06-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_financesettings_job_claims_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='chat_sessions_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
