# Generated by Django 6.0.6 on 2026-06-28 19:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('credited', 'Credited'), ('reversed', 'Reversed'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('release_at', models.DateTimeField()),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activation_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='referral_bonus', to='payments.mpesatransaction')),
                ('ledger_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_bonus', to='wallets.ledgertransaction')),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earned_referral_bonuses', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_bonuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['referrer', 'status'], name='referrals_r_referre_ba3099_idx'), models.Index(fields=['referred_user'], name='referrals_r_referre_f6d03b_idx'), models.Index(fields=['status', 'release_at'], name='referrals_r_status_c7fe53_idx')],
            },
        ),
    ]
