# Generated by Django 6.0.6 on 2026-06-28 19:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('locked_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('deposit_confirmed', 'Deposit confirmed'), ('activation_credit', 'Activation credit'), ('referral_bonus_pending', 'Referral bonus pending'), ('referral_bonus_available', 'Referral bonus available'), ('job_reward_pending', 'Job reward pending'), ('job_reward_approved', 'Job reward approved'), ('product_commission', 'Product commission'), ('withdrawal_requested', 'Withdrawal requested'), ('withdrawal_paid', 'Withdrawal paid'), ('withdrawal_failed', 'Withdrawal failed'), ('admin_adjustment', 'Admin adjustment'), ('fraud_hold', 'Fraud hold'), ('system_reversal', 'System reversal')], max_length=40)),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('balance_bucket', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('locked', 'Locked')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('reversed', 'Reversed'), ('void', 'Void')], default='posted', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('source_app', models.CharField(blank=True, max_length=80)),
                ('source_model', models.CharField(blank=True, max_length=120)),
                ('source_id', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ledger_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_transactions', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user'], name='wallets_wal_user_id_006796_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('available_balance__gte', 0), ('pending_balance__gte', 0), ('locked_balance__gte', 0), ('total_earned__gte', 0), ('total_withdrawn__gte', 0)), name='wallet_balances_non_negative'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['user', '-created_at'], name='wallets_led_user_id_620f05_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='wallets_led_transac_489927_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['status', '-created_at'], name='wallets_led_status_8baf53_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['source_app', 'source_model', 'source_id'], name='wallets_led_source__4547d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgertransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledger_amount_positive'),
        ),
    ]
