# Generated by Django 6.0.6 on 2026-06-28 19:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('payout_reference', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_credit_ledger', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_lock_credit', to='wallets.ledgertransaction')),
                ('paid_ledger', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_paid', to='wallets.ledgertransaction')),
                ('release_available_ledger', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_release_available', to='wallets.ledgertransaction')),
                ('release_locked_ledger', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_release_locked', to='wallets.ledgertransaction')),
                ('request_debit_ledger', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_request_debit', to='wallets.ledgertransaction')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='wallets_wit_user_id_dfd6dc_idx'), models.Index(fields=['status', '-created_at'], name='wallets_wit_status_1b8ada_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='withdrawal_amount_positive'), models.CheckConstraint(condition=models.Q(('fee__gte', 0)), name='withdrawal_fee_non_negative'), models.CheckConstraint(condition=models.Q(('net_amount__gte', 0)), name='withdrawal_net_amount_non_negative')],
            },
        ),
    ]
