# Generated by Django 6.0.6 on 2026-06-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_withdrawalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit_confirmed', 'Deposit confirmed'), ('activation_credit', 'Activation credit'), ('referral_bonus_pending', 'Referral bonus pending'), ('referral_bonus_available', 'Referral bonus available'), ('job_reward_pending', 'Job reward pending'), ('job_reward_approved', 'Job reward approved'), ('product_purchase', 'Product purchase'), ('product_commission', 'Product commission'), ('withdrawal_requested', 'Withdrawal requested'), ('withdrawal_paid', 'Withdrawal paid'), ('withdrawal_failed', 'Withdrawal failed'), ('admin_adjustment', 'Admin adjustment'), ('fraud_hold', 'Fraud hold'), ('system_reversal', 'System reversal')], max_length=40),
        ),
    ]
