# Generated by Django 6.0.6 on 2026-06-28 21:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0003_alter_ledgertransaction_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'product categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('product_type', models.CharField(choices=[('digital_file', 'Digital file'), ('external_link', 'External link'), ('service', 'Service/manual delivery')], default='digital_file', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('summary', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cover_image', models.FileField(blank=True, upload_to='products/covers/%Y/%m/')),
                ('download_file', models.FileField(blank=True, upload_to='products/files/%Y/%m/')),
                ('external_url', models.URLField(blank=True)),
                ('stock_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('sold_count', models.PositiveIntegerField(default=0)),
                ('commission_type', models.CharField(choices=[('none', 'No commission'), ('fixed', 'Fixed amount'), ('percent', 'Percentage')], default='none', max_length=20)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('commission_release_delay_hours', models.PositiveIntegerField(default=24)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('delivery_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_purchase', to='wallets.ledgertransaction')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('credited', 'Credited'), ('reversed', 'Reversed'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('release_at', models.DateTimeField()),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_product_commissions', to=settings.AUTH_USER_MODEL)),
                ('ledger_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_commission', to='wallets.ledgertransaction')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_commissions', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission', to='products.productpurchase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'product_type'], name='products_pr_status_873e9e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='products_pr_categor_75eeb5_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='product_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('commission_amount__gte', 0)), name='product_commission_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('commission_percent__gte', 0)), name='product_commission_percent_non_negative'),
        ),
        migrations.AddIndex(
            model_name='productpurchase',
            index=models.Index(fields=['user', 'status'], name='products_pr_user_id_8b0e93_idx'),
        ),
        migrations.AddIndex(
            model_name='productpurchase',
            index=models.Index(fields=['product', 'status'], name='products_pr_product_31ce56_idx'),
        ),
        migrations.AddIndex(
            model_name='productpurchase',
            index=models.Index(fields=['status', '-created_at'], name='products_pr_status_a197f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='productpurchase',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='product_purchase_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productpurchase',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='one_purchase_per_user_per_product'),
        ),
        migrations.AddIndex(
            model_name='productcommission',
            index=models.Index(fields=['referrer', 'status'], name='products_pr_referre_ab5d12_idx'),
        ),
        migrations.AddIndex(
            model_name='productcommission',
            index=models.Index(fields=['status', 'release_at'], name='products_pr_status_682bed_idx'),
        ),
        migrations.AddConstraint(
            model_name='productcommission',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='product_commission_amount_positive'),
        ),
    ]
