# Generated by Django 6.0.6 on 2026-06-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content_format',
            field=models.CharField(choices=[('guide', 'Guide'), ('story', 'Story'), ('article', 'Article'), ('video', 'Video'), ('template', 'Template'), ('file', 'File/resource'), ('link', 'Link resource'), ('service', 'Service')], default='file', max_length=30),
        ),
    ]
